# -*- coding: utf-8 -*-
"""CRAWL DATA DINA (FIX).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QevswDzVYBMYve0cWRbetHbSTThU-L3l
"""

#@title Twitter Auth Token

twitter_auth_token = 'auth' # change this auth token

!pip install pandas

!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main"
| sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

filename = 'bencana.csv'
search_keyword = '(gempa OR banjir OR longsor OR BMKG OR cuaca OR erupsi OR puting beliung) since:2025-05-01 until:2025-05-07 lang:id'
limit = 200

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token "{twitter_auth_token}"

filename = 'politik.csv'
search_keyword = '(pilpres OR capres OR koalisi OR pemilu OR debat politik OR anies OR prabowo OR ganjar) since:2025-05-01 until:2025-05-07 lang:id'
limit = 200

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token "{twitter_auth_token}"